# About the Authors

## Brandon Rose, MD, MPH

Dr. Rose earned his MD/MPH at the University of Miami Miller School of Medicine. He is currently a third-year internal medicine resident at Jackson Memorial Hospital and is a rising fellow in hematology and oncology at the University of Texas Southwestern Medical Center. He specializes in clinical data pipelines and R computer programming and is passionate about precision oncology, disparities research, and quality improvement. He has led numerous projects with sarcoma, thoracic oncology, neuroendocrine tumor, and the Firefighter Cancer Initiative.

## Natalie Goulett, BS

Natalie is a healthcare simulation operations specialist and MPH student majoring in biostatistics at Florida International University. As a data science instructor, Natalie helps investigators conduct efficient and reproducible research using R. Her research interests include the impact of occupational hazards on first responders and the promotion of equity and quality improvement in research. Outside of her academic pursuits, Natalie enjoys live music and scuba diving.

##

